# Generated by Django 3.2.9 on 2021-11-13 12:20

from django.conf import settings
from django.db import migrations, models
import markdownx.models
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('short_desc', models.CharField(max_length=255, verbose_name='Short Description')),
                ('content', markdownx.models.MarkdownxField()),
                ('pub_on', models.DateTimeField(auto_now_add=True, verbose_name='Published On')),
                ('reporter', models.ForeignKey(on_delete=models.SET(news.models.get_deleted_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
